version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '5000:5000'

    env_file: .env

    environment:
      - REDIS_HOST=redis
      - PORT=5000

    depends_on:
      - redis
  redis:
    image: redis:latest
